# Travis config for @RsrchBoy's p5 packages.
#
# Kinda.
#
# GistID: 31e0e356a6233e5ee730
# Chris Weyl <cweyl@alumni.drew.edu> 2015

# use the docker/container based infrastructure
sudo: false

language: perl
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"
   - "5.20"

matrix:
   allow_failures:
      - perl: "5.8"

branches:
    except:
        - "release/cpan"

env:
   global:
      - CPANM_OPTS="-q --skip-satisfied --notest --no-man-pages"

before_install:
   # git bits sometimes needed...
   - git config user.name 'Travis-CI'
   - git config user.email 'travis@nowhere.dne'

   # pull down our cache
   - wget https://raw.githubusercontent.com/RsrchBoy/travis-p5-cache/master/fetch-cache
   - source ./fetch-cache

   # for DZP LinkCheck
   - cpanm $CPANM_OPTS CPANPLUS || { cat ~/.cpanm/build.log ; false ; }
   - cpanp x

install:
   # not so much install our package as all its prereqs
   - cpanm --with-develop -q --skip-satisfied --no-man-pages 
   - dzil authordeps --missing        | cpanm $CPANM_OPTS        || { cat ~/.cpanm/build.log ; false ; }
   - dzil listdeps --author --missing | cpanm -q --skip-satisfied || { cat ~/.cpanm/build.log ; false ; }

script:
   - export DZSIGN=archive
   - unset HARNESS_SUBCLASS
   - dzil test --all
